version: '2'
services:
  blog-mysql:
    image: mysql:5.6
    volumes:
         - c:/dev/volumes/blog/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=blog
    ports:
      - 3306:3306

